# .goreleaser.yml
---
archive:
  format: binary
builds:
  -
    binary: tpmtool
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X "main.goversion={{.Env.GOVERSION}}"
    goarch:
      - 386
      - amd64
      - arm64
      - arm
    goos:
      - linux
    goarm:
      - 7
    main: "."
    hooks:
      post:
        - upx --best --ultra-brute dist/linux_amd64/tpmtool
        - upx --best --ultra-brute dist/linux_arm_7/tpmtool
        - upx --best --ultra-brute dist/linux_386/tpmtool
        - upx --best --ultra-brute dist/linux_arm64/tpmtool
nfpm:
  vendor: Facebook Inc.
  homepage: www.tpmtool.org
  maintainer: Philipp Deppenwiese <philipp.deppenwiese@9elements.com>
  description: A Linux only tool for TPM interaction
  license: BSD-3
  formats:
    - deb
    - rpm
  dependencies:
    - cryptsetup
project_name: tpmtool
sign:
  artifacts: checksum
